version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - audio-calling-network

networks:
  audio-calling-network:
    driver: bridge